### ISSUE TITLE
HACD mining

### ISSUE THREAD

**Issue by RustMan88** [hacash/rust#1]
"This project does not implement HACD mining. I need HACD mining. When will you be able to integrate this feature?"

**Comment by jojoin** [comment]
There are plans to develop a HACD mining program. However, it may be necessary to wait until the existing version is more stable and there are no problems in all aspects of functional testing before developing HACD mining.

**Comment by RustMan88** [comment]
Good job

**Comment by jojoin** [comment]
HACD mining for now.
https://github.com/hacash/rust/releases/tag/v0.1.1
