### ISSUE TITLE
About HVM

### ISSUE THREAD

**Issue by yita0101** [hacash/rust#3]
When will the HVM be implemented, I would like to deploy some decentralized trading activities by HVM.Or is there an API  to support such transactions now? For example,I pay a hacd into a person's address, and then I received a HAC payment.

**Comment by jojoin** [comment]
This kind of atomic transaction does not require the support of a VM, just use Hacash's readable contract:

**Comment by yita0101** [comment]
I read this carefully, but I have a doubt, what if the buyer's address is unknown before the purchase?

**Comment by jojoin** [comment]
This requirement really can't be achieved with readable contracts, and requires a higher level of programmability (HVM).

For example, a HACD seller's order book can place orders at a fixed price, and the buyer can click to buy and automatically get HACD after paying for HAC. This requires more advanced smart contracts.

**Comment by yita0101** [comment]
I understood, thank you for your answer. I have another question, I don't understand the code about the real-time trading part, is there a code example to show the process?
![image](https://github.com/user-attachments/assets/4d91a64b-1a47-4e21-9e1f-b2083dc5df55)
