### ISSUE TITLE
Fail to build wasm module

### ISSUE THREAD

**Issue by yita0101** [hacash/rust#5]
I try to build the sdk  by the order "wasm-pack --log-level error build --target no-modules",it not compile and follow the error:
![image](https://github.com/user-attachments/assets/053cbe6f-b7a4-415e-9888-15a3143d56ae)

**Comment by yita0101** [comment]
the mio crate seems not support wasm

**Comment by yita0101** [comment]
the sdk module also seems not complie all modules,how do I decouple and compile it?

**Comment by jojoin** [comment]
This version of the Rust code has not yet been adapted to WASM and awaits further work.

**Comment by yita0101** [comment]
I tried to decouple some modules,and  now it's ready to be build by the order 'wasm-pack build --target web'.
But to run the order 'wasm-pack test --headless --chrome' has some problem.
I have push it at https://github.com/yita0101/hacash_web_api_template.git
![image](https://github.com/user-attachments/assets/6590381a-e71b-4cd8-9499-17039169426c)

**Comment by yita0101** [comment]
the method TransactionType2::build seem not run on wasm.
![image](https://github.com/user-attachments/assets/a80c4b22-8840-47fc-9097-716d5ebe5f45)
