### ISSUE TITLE
Serious problem !!!

### ISSUE THREAD

**Issue by yita0101** [hacash/rust#7]
I tried to calculate the hash of the block with the available information, and found that the calculation did not match

[http://nodeapi.hacash.org/query/block/intro?height=591819](http://nodeapi.hacash.org/query/block/intro?height=591819)
{
    "ret": 0,
    "hash": "000000000018c7925c3d67f81fd514b79430cd10896a2d8208c72b572f3d1cd5",
    "message": "HOPE",
    "height": 591819,
    "timestamp": 1728568347,
    "prevhash": "0000000000025c1c65571d0db3c040e28d3a3b515746f45e95c9092f3e8cf52d",
    "version": 1,
    "mrklroot": "1c29dae6df06d03d8e94ffc36a05f86311277c719c9a7cc404af6dec3456b339",
    "difficulty": 3571002440,
    "miner": "12FeQ7pgof6y5f7G8TJYeesso9u88MTpA8",
    "reward": "8:248",
    "transaction": 0,
    "nonce": 2779876024
}

0100000907cb006707dc1b0000000000025c1c65571d0db3c040e28d3a3b515746f45e95c9092f3e8cf52d1c29dae6df06d03d8e94ffc36a05f86311277c719c9a7cc404af6dec3456b33900000000a5b18ab8d4d92c480000

01 blockversion 1
00000907cb height 5
006707dc1b timestamp 5
0000000000025c1c65571d0db3c040e28d3a3b515746f45e95c9092f3e8cf52d prehash 32
1c29dae6df06d03d8e94ffc36a05f86311277c719c9a7cc404af6dec3456b339 mrklroot 32
00000000  tscount 4
a5b18ab8  nonce 4
d4d92c48 difficulty 4
0000 2

sha3:e73b5b48d50c840b23266639245e3fc95673a8dcc9288a50e0e54f8461844557
x16rs:12b3bdb076ecc6a266b4dfd2911b67e9493e93bba8f2eaa71655598c9a5a8bf9

execution source code:
[main_x16rs.zip](https://github.com/user-attachments/files/17342589/main_x16rs.zip)

**Comment by jojoin** [comment]
intToarr(timestamp, tempbytes, 4);
 temp=hex_encode(tempbytes, 4);
 strcat(stuff_hex,temp );

--------------------

ERROR: timestamp bytes length is 5.

**Comment by jojoin** [comment]
`unsigned int tscount= 0;`

-------- change to --------

`unsigned int tscount= 1;`

Because there is not 0 transactions in the block, but there is a coinbase transaction, so `tscount` field is always more than or equal to 1.

**Comment by yita0101** [comment]
I think it would be better to modify the "transaction" value to avoid misunderstandings in the next version of the api.
