### ISSUE TITLE
"pending block not yet" and "diamond XXX not belong to address YYY" when successfully mining a block

### ISSUE THREAD

**Issue by Iv-84** [hacash/rust#9]
Dear repository admins,

Last week I found like 4 or 5 blocks but the response from the rust node was always `pending block not yet`
Also, the node console displays `diamond ESEMEE not belong to address 1M4fzD5U8tmNH5KAueSvaKhS9UDSNojSu1`
Looking at explorer.hacash.org, my block is added but is a fork.

The poworker request URL seems correct:
http://localhost:8081/submit/miner/success?height=604679&block_nonce=1985880205&coinbase_nonce=734cb8c52aa520c1e42aaa5fba67ebc9e829fcc1feef1859158901d06e236905

I tried this and didn't work:
 - Version [v0.1.2](https://github.com/hacash/rust/releases/tag/v0.1.2) on Windows 64 and Ubuntu
 - Version [v0.1.1](https://github.com/hacash/rust/releases/tag/v0.1.1) on Windows 64
 - Compiling "main" branch on Windows 64 and Ubuntu
 - Deleting and rebuilding folder "hacash_mainnet_data"

**Comment by Iv-84** [comment]
This is an screenshot from the console.

![image](https://github.com/user-attachments/assets/b040df4c-0178-42b9-b4ec-d96bebe743bc)

Thanks in advance.

**Comment by jojoin** [comment]
It seems there is a bug here. The block you mined contains 99 transactions, which clearly does not align with the current network conditions. Incorrect transactions are included in the block you mined.

Please move to the [hacash/fullnode](https://github.com/hacash/fullnode) codebase for discussion, the latest version is built here, and future development and releases are made within this repo.
